### ISSUE TITLE
Question about thumos14 dataset and Thumos14reduced dataset

### ISSUE THREAD

**Issue by lizhilin-ustc** [LeonHLJ/RSKP#6]
Thank you for your good work!
I'm just getting into this field, and I want to ask why some works use thumos14 dataset and some works use Thumos14reduced dataset. Are these two datasets exactly the same?

**Comment by LeonHLJ** [comment]
> Thank you for your good work! I'm just getting into this field, and I want to ask why some works use thumos14 dataset and some works use Thumos14reduced dataset. Are these two datasets exactly the same?

Thanks for your interest in our work. Actually, THUMOS14reduced is a subset of the THUMOS14 dataset. The THUMOS14 dataset has 101 classes for action recognition and 20 classes for action detection. There are no differences between the so-called THUMOS14 and THUMOS14reduced in the papers for this task, since for temporal action detection, we can only use those videos with temporal annotations (20 classes), which compose the THUMOS14reduced dataset.

**Comment by lizhilin-ustc** [comment]
> Thank you for your help!
